# Generated by Django 2.2.8 on 2020-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200128_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_specific',
            field=models.BooleanField(default=False, help_text='Group product order by order type', verbose_name='Is specific'),
        ),
    ]
