# Generated by Django 2.2.8 on 2020-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_is_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_specific',
            field=models.BooleanField(default=False, editable=False, help_text='Group product order by order type', verbose_name='Is specific'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('trash', 'Trash'), ('draft', 'Draft'), ('valid', 'Valid'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('process', 'Process'), ('complete', 'Complete'), ('closed', 'Closed')], default='draft', editable=False, max_length=15, verbose_name='Status'),
        ),
    ]
