# Generated by Django 2.2.8 on 2020-01-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200128_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
