# Generated by Django 2.2.8 on 2020-01-29 11:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_orderproduct_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='sales.Order', verbose_name='Order'),
        ),
    ]
