# Generated by Django 2.2.10 on 2020-02-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureForStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lecturestudent',),
        ),
    ]
