# Generated by Django 2.2.10 on 2020-02-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lectureschedule',),
        ),
    ]
