# Generated by Django 2.2.10 on 2020-02-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_coach'),
        ('lectures', '0001_initial'),
        ('intranet', '0002_studentschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSchedule',
        ),
        migrations.CreateModel(
            name='ScheduleForStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lectureschedule',),
        ),
        migrations.CreateModel(
            name='ScoreForStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentscore',),
        ),
    ]
