# Generated by Django 2.2.8 on 2020-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_prospective_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_prospective_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_prospective_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
