# Generated by Django 2.2.10 on 2020-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_graduate',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Year graduate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_education_level',
            field=models.CharField(choices=[('0', 'SD'), ('1', 'SMP'), ('2', 'SMA'), ('3', 'D1'), ('4', 'D2'), ('5', 'D3'), ('6', 'D4'), ('7', 'S1'), ('8', 'S2'), ('9', 'S3')], default='2', max_length=5, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_education_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Major'),
        ),
    ]
