# Generated by Django 2.2.8 on 2020-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200126_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
    ]
