# Generated by Django 2.2.8 on 2020-02-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200207_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_prospective_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
