# Generated by Django 2.2.8 on 2020-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200207_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_prospective_employee',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_prospective_partner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_prospective_student',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_prospective_teacher',
        ),
        migrations.AddField(
            model_name='person',
            name='is_employee_applicant',
            field=models.BooleanField(default=False, verbose_name='Employee applicant?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_matriculant',
            field=models.BooleanField(default=False, verbose_name='Matriculant?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_partner_applicant',
            field=models.BooleanField(default=False, verbose_name='Partner applicant?'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_teacher_applicant',
            field=models.BooleanField(default=False, verbose_name='Teacher applicant?'),
        ),
    ]
