# Generated by Django 2.2.8 on 2020-01-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200126_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personsettings',
            options={'verbose_name': 'Person Setting', 'verbose_name_plural': 'Person Settings'},
        ),
    ]
