# Generated by Django 2.2.10 on 2020-02-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20200217_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonSettings',
        ),
    ]
