# Generated by Django 2.2.8 on 2020-02-07 19:54

from django.db import migrations, models
import wagtailkit.persons.models.extra


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20200207_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaleducation',
            name='level',
            field=models.CharField(choices=[('0', 'SD'), ('1', 'SMP'), ('2', 'SMA'), ('3', 'D1'), ('4', 'D2'), ('5', 'D3'), ('6', 'D4'), ('7', 'S1'), ('8', 'S2'), ('9', 'S3')], default=wagtailkit.persons.models.extra.KKNILevel('7'), max_length=3, verbose_name='Level'),
        ),
    ]
