# Generated by Django 2.2.8 on 2020-02-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20200208_0254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formaleducation',
            unique_together=set(),
        ),
    ]
