# Generated by Django 2.2.8 on 2020-02-08 09:59

from django.db import migrations, models
import wagtailkit.persons.models.extra


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20200208_0256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.AddField(
            model_name='person',
            name='last_education_level',
            field=models.CharField(choices=[('0', 'SD'), ('1', 'SMP'), ('2', 'SMA'), ('3', 'D1'), ('4', 'D2'), ('5', 'D3'), ('6', 'D4'), ('7', 'S1'), ('8', 'S2'), ('9', 'S3')], default=wagtailkit.persons.models.extra.KKNILevel('2'), max_length=3, verbose_name='Edu Level'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_education_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Edu Name'),
        ),
    ]
