# Generated by Django 2.2.8 on 2020-02-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20200208_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('export_person', 'Can export Person'), ('import_person', 'Can import Person'), ('change_status_person', 'Can change status Person')), 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
