# Generated by Django 2.2.8 on 2020-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20200210_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nick name'),
        ),
    ]
