# Generated by Django 2.2.8 on 2020-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
