# Generated by Django 2.2.8 on 2020-01-15 01:51

from django.db import migrations, models
import django.utils.timezone
import uuid
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('metafield', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Metafield')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('is_single', models.BooleanField(default=True, verbose_name='Single chair')),
                ('employee_required', models.IntegerField(default=1, verbose_name='Employee required')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Description of Duty')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Chair',
                'verbose_name_plural': 'Chairs',
            },
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('metafield', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Metafield')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Primary')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Chairman',
                'verbose_name_plural': 'Chairmans',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('metafield', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Metafield')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('metafield', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Metafield')),
                ('eid', models.CharField(max_length=128, unique=True, verbose_name='Employee ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('note', models.TextField(blank=True, max_length=512, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employments',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
