# Generated by Django 2.2.8 on 2020-02-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20200208_0256'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonAsEmployee',
        ),
        migrations.CreateModel(
            name='EmployeePersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Employee Personal',
                'verbose_name_plural': 'Employee Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
    ]
