# Generated by Django 2.2.8 on 2020-01-15 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtaildocs', '0010_document_file_hash'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAsEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.AddField(
            model_name='employee',
            name='attachment',
            field=models.ForeignKey(blank=True, help_text='Contract Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.Employment', verbose_name='Employment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='department',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_upline', to='employees.Department', verbose_name='Upline'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='chair',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Chair', verbose_name='Chair'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='employee',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='employees.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='chair',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='chair',
            name='department',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='chair',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chair_upline', to='employees.Chair', verbose_name='Upline'),
        ),
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.AlterUniqueTogether(
            name='chairman',
            unique_together={('employee', 'chair')},
        ),
    ]
