# Generated by Django 2.2.10 on 2020-02-14 20:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('organizations', '0001_initial'),
        ('employees', '0001_initial'),
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraposition',
            name='position',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_chairmans', to='organizations.Position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='attachment',
            field=models.ForeignKey(blank=True, help_text='Contract Document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.Employment', verbose_name='Employment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chairmans', to='organizations.Position', verbose_name='Position'),
        ),
        migrations.AlterUniqueTogether(
            name='extraposition',
            unique_together={('employee', 'position')},
        ),
    ]
