# Generated by Django 2.2.8 on 2020-02-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200208_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_education_level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_education_name',
        ),
    ]
