# Generated by Django 2.2.8 on 2020-02-11 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200208_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date registered'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chairmans', to='organizations.Position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='extraposition',
            name='position',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_chairmans', to='organizations.Position', verbose_name='Position'),
        ),
    ]
