# Generated by Django 2.2.8 on 2020-01-28 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simpellab.products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_productcategory_inner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('service_type', models.CharField(choices=[('LAB', 'Laboratorium Uji'), ('LIT', 'Inspeksi Teknis'), ('KAL', 'Kalibrasi'), ('LIB', 'Litbang'), ('KSL', 'Konsultansi'), ('PRO', 'Sertifikasi Produk'), ('LAT', 'Pelatihan'), ('LNY', 'Lainnya')], default=simpellab.products.models.ServiceType('Laboratorium Uji'), max_length=3, verbose_name='Service Type')),
            ],
            options={
                'verbose_name': 'Lab Service',
                'verbose_name_plural': 'Lab Service',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('service_type', models.CharField(choices=[('LAB', 'Laboratorium Uji'), ('LIT', 'Inspeksi Teknis'), ('KAL', 'Kalibrasi'), ('LIB', 'Litbang'), ('KSL', 'Konsultansi'), ('PRO', 'Sertifikasi Produk'), ('LAT', 'Pelatihan'), ('LNY', 'Lainnya')], default=simpellab.products.models.ServiceType('Laboratorium Uji'), max_length=3, verbose_name='Service Type')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='simpellabproducts.LabService', verbose_name='Product')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpellabproducts.Tarif', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'unique_together': {('product', 'tarif')},
            },
        ),
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Price')),
                ('date_effective', models.DateField(default=django.utils.timezone.now, verbose_name='Date effective')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpellabproducts.Fee', verbose_name='Extra Fee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fees', to='simpellabproducts.LabService', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Extra Fee',
                'verbose_name_plural': 'Extra Fees',
                'unique_together': {('product', 'fee')},
            },
        ),
    ]
