# Generated by Django 2.2.8 on 2020-01-28 16:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simpellabproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafee',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='extrafee',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fees', to='simpellabproducts.LabService', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='simpellabproducts.LabService', verbose_name='Product'),
        ),
    ]
