# Generated by Django 2.2.10 on 2020-02-21 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('teachers', '0003_auto_20200217_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
                ('name', models.CharField(max_length=512, verbose_name='Note')),
                ('note', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
            ],
            options={
                'verbose_name': 'Lecture Attendance',
                'verbose_name_plural': 'Lecture Attendances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lectureschedule',),
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('PR', 'PRESENT'), ('SC', 'SICK'), ('AB', 'ABSENT'), ('PE', 'PERMIT')], default='AB', max_length=3, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Note')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.LectureSchedule', verbose_name='Schedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'unique_together': {('schedule', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('PR', 'PRESENT'), ('SC', 'SICK'), ('AB', 'ABSENT'), ('PE', 'PERMIT')], default='AB', max_length=3, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=512, null=True, verbose_name='Note')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.LectureSchedule', verbose_name='Schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lectures.LectureStudent', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendances',
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
