# Generated by Django 2.2.8 on 2020-01-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
            ],
            options={
                'verbose_name': 'Lecture Attendance',
                'verbose_name_plural': 'Lecture Attendances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lectures.lectureschedule',),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.LectureSchedule', verbose_name='Schedule'),
        ),
    ]
