# Generated by Django 2.2.8 on 2020-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_auto_20200130_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('PR', 'Present'), ('SC', 'Sick'), ('AB', 'Absent'), ('PE', 'Permit')], default='PR', max_length=3, verbose_name='Status'),
        ),
    ]
