# Generated by Django 2.2.10 on 2020-02-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_auto_20200223_1833'),
        ('intranet_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentPlan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.enrollmentplan',),
        ),
    ]
