# Generated by Django 2.2.10 on 2020-02-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_enrollmentplan_creator'),
        ('intranet_students', '0003_lectureoffered'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enrollments.enrollment',),
        ),
    ]
