# Generated by Django 2.2.8 on 2020-01-29 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvalQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('question', wagtail.core.fields.RichTextField(max_length=10000, verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Eval Question',
                'verbose_name_plural': 'Eval Questions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EvalQuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('code', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', wagtail.core.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Eval Question Group',
                'verbose_name_plural': 'Eval Question Groups',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('questions', models.ManyToManyField(related_name='evaluations', to='evaluations.EvalQuestion', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.AddField(
            model_name='evalquestion',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.EvalQuestionGroup', verbose_name='Question group'),
        ),
    ]
