# Generated by Django 2.2.8 on 2020-01-27 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureevaluation',
            options={'verbose_name': 'Lecture Evaluation', 'verbose_name_plural': 'Lecture Evaluations'},
        ),
        migrations.AddField(
            model_name='evalquestiongroup',
            name='code',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='code'),
        ),
    ]
