# Generated by Django 2.2.8 on 2020-01-27 13:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_auto_20200127_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalquestiongroup',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Description'),
        ),
    ]
