# Generated by Django 2.2.8 on 2020-01-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20200127_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureevaluationscore',
            name='lecture_evaluation',
        ),
        migrations.RemoveField(
            model_name='lectureevaluationscore',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='evalquestion',
            options={'ordering': ['-date_created'], 'verbose_name': 'Eval Question', 'verbose_name_plural': 'Eval Questions'},
        ),
        migrations.DeleteModel(
            name='LectureEvaluation',
        ),
        migrations.DeleteModel(
            name='LectureEvaluationScore',
        ),
    ]
