# Generated by Django 2.2.8 on 2020-01-29 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start', models.DateField(default=datetime.datetime(2019, 12, 31, 17, 0, tzinfo=utc), verbose_name='Fiscal year start')),
                ('fiscal_year_end', models.DateField(default=django.utils.timezone.now, verbose_name='Fiscal year end')),
                ('name', models.CharField(blank=True, help_text='Your company name', max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, help_text='Your company tagline', max_length=255, null=True)),
                ('website', models.CharField(blank=True, help_text='Website URL.', max_length=255, null=True)),
                ('sitename', models.CharField(blank=True, help_text='Site name, widely used in this site.', max_length=255, null=True)),
                ('street1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 1')),
                ('street2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, help_text='Phone number @', max_length=255, null=True)),
                ('fax', models.CharField(blank=True, help_text='Fax number @', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Valid email', max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter', models.CharField(blank=True, help_text='twitter username, without the @', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram username, without the @', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel or user account URL', null=True)),
                ('logo', models.ForeignKey(blank=True, help_text='Your company Logo (square, transparent baground is better)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
    ]
