# Generated by Django 2.2.10 on 2020-02-14 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailkitcore', '0003_auto_20200214_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='fiscal_year_start',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=utc), verbose_name='Fiscal year start'),
        ),
    ]
