# Generated by Django 2.2.8 on 2020-02-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_create_warehouse_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_wh_requests', to='organizations.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_wh_requests', to='organizations.Position', verbose_name='Requester'),
        ),
    ]
