# Generated by Django 2.2.10 on 2020-03-03 04:11

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200217_0336'),
        ('warehouse', '0003_auto_20200217_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='validator',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_wh_requests', to='employees.Employee', verbose_name='Validator'),
        ),
    ]
