# Generated by Django 2.2.8 on 2020-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200126_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
    ]
