# Generated by Django 2.2.8 on 2020-02-10 11:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200208_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='department',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_wh_requests', to='organizations.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='requester',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_wh_requests', to='organizations.Position', verbose_name='Requester'),
        ),
    ]
