# Generated by Django 2.2.10 on 2020-03-03 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0004_requestorder_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransfer',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttransfer_completed_by', to=settings.AUTH_USER_MODEL, verbose_name='Completed by'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date processed'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='date_trashed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validated'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttransfer_processed_by', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttransfer_trashed_by', to=settings.AUTH_USER_MODEL, verbose_name='Trashed by'),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttransfer_validated_by', to=settings.AUTH_USER_MODEL, verbose_name='Validated by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_completed_by', to=settings.AUTH_USER_MODEL, verbose_name='Completed by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date approved'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date completed'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date processed'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date rejected'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_trashed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date validated'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_processed_by', to=settings.AUTH_USER_MODEL, verbose_name='Processed by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_rejected_by', to=settings.AUTH_USER_MODEL, verbose_name='Rejected by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_trashed_by', to=settings.AUTH_USER_MODEL, verbose_name='Trashed by'),
        ),
        migrations.AddField(
            model_name='requestorder',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestorder_validated_by', to=settings.AUTH_USER_MODEL, verbose_name='Validated by'),
        ),
    ]
