# Generated by Django 2.2.8 on 2020-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20200127_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AlterField(
            model_name='productstorage',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
    ]
