# Generated by Django 2.2.10 on 2020-03-03 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0005_auto_20200303_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_validator', to='employees.Employee', verbose_name='Validator'),
        ),
        migrations.AlterIndexTogether(
            name='requestorder',
            index_together={('inner_id', 'creator')},
        ),
    ]
