# Generated by Django 2.2.10 on 2020-02-15 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionscore',
            options={'verbose_name': 'Conversion Score', 'verbose_name_plural': 'Conversion Scores'},
        ),
        migrations.AlterField(
            model_name='conversionscore',
            name='ori_numeric_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Origin Numeric Score'),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_students', to='lectures.Lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='students.Student', verbose_name='Student'),
        ),
    ]
