# Generated by Django 2.2.10 on 2020-02-25 20:32

from django.db import migrations, models
import wagtailkit.lectures.models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('REG', 'Registration'), ('PRE', 'Preparation'), ('ONG', 'Ongoing'), ('END', 'End'), ('CMP', 'Complete')], default=wagtailkit.lectures.models.LectureStatus('PND'), max_length=3, verbose_name='Status'),
        ),
    ]
