# Generated by Django 2.2.10 on 2020-02-15 16:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20200215_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturestudent',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='lecture',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.Lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_students', to='students.Student', verbose_name='Student'),
        ),
    ]
