# Generated by Django 2.2.8 on 2020-01-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20200127_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureschedule',
            name='type',
            field=models.CharField(choices=[('1', 'Meeting'), ('2', 'E-Learning'), ('99', 'Subtitution'), ('3', 'Mid Exam'), ('4', 'Final Exam')], default='1', max_length=3, verbose_name='Type'),
        ),
    ]
