# Generated by Django 2.2.10 on 2020-02-15 16:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20200215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturestudent',
            name='lecture',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.Lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='students.Student', verbose_name='Student'),
        ),
    ]
