# Generated by Django 2.2.8 on 2020-01-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20200127_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureStudentAttendance',
        ),
        migrations.DeleteModel(
            name='LectureStudentScore',
        ),
    ]
