# Generated by Django 2.2.8 on 2020-01-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_registration'),
        ('teachers', '0004_auto_20200127_1248'),
        ('lectures', '0007_auto_20200127_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureStudentAttendant',
            new_name='StudentAttendance',
        ),
        migrations.RenameModel(
            old_name='LectureTeacherAttendant',
            new_name='TeacherAttendance',
        ),
    ]
