# Generated by Django 2.2.8 on 2020-01-27 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0004_auto_20200127_2151'),
        ('students', '0005_student_registration'),
        ('lectures', '0010_teacherattendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.Evaluation', verbose_name='Evaluation')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.Lecture', verbose_name='Lecture')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Lecture Evaluation',
                'verbose_name_plural': 'Lecture Evaluations',
            },
        ),
        migrations.CreateModel(
            name='LectureEvaluationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('score', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1:Tidak Setuju > 5:Setuju', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('lecture_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.LectureEvaluation', verbose_name='Lecture evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.EvalQuestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Lecture Evaluation Score',
                'verbose_name_plural': 'Lecture Evaluation Scores',
                'ordering': ('question__group__code', 'question__date_created'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
