# Generated by Django 2.2.8 on 2020-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_auto_20200127_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='attendance',
            field=models.PositiveIntegerField(default=15, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='final_exam',
            field=models.PositiveIntegerField(default=25, verbose_name='Final Exam'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='homework1',
            field=models.PositiveIntegerField(default=10, verbose_name='Homework 1'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='homework2',
            field=models.PositiveIntegerField(default=10, verbose_name='Homework 2'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='mid_exam',
            field=models.PositiveIntegerField(default=20, verbose_name='Mid Exam'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='quis1',
            field=models.PositiveIntegerField(default=10, verbose_name='Quis 1'),
        ),
        migrations.AlterField(
            model_name='lecturescoreweighting',
            name='quis2',
            field=models.PositiveIntegerField(default=10, verbose_name='Quis 2'),
        ),
    ]
