# Generated by Django 2.2.8 on 2020-02-14 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'permissions': (('export_partnerpersonal', 'Can export Person Personal'), ('import_partnerpersonal', 'Can import Person Personal')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.AddField(
            model_name='suppliercontactperson',
            name='supplier',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contactpersons', to='partners.Supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnercontactinfo',
            name='partner',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='partner',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='customercontactperson',
            name='customer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contactpersons', to='partners.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partners.Partner', verbose_name='Partner'),
        ),
    ]
