# Generated by Django 2.2.8 on 2020-02-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20200208_1659'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonAsPartner',
        ),
        migrations.CreateModel(
            name='PartnerPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'permissions': (('export_partnerpersonal', 'Can export Person Personal'), ('import_partnerpersonal', 'Can import Person Personal')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
    ]
