# Generated by Django 2.2.8 on 2020-02-08 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('persons', '0009_auto_20200208_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAsStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Student Personal',
                'verbose_name_plural': 'Student Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('sid', models.CharField(editable=False, max_length=128, unique=True, verbose_name='Student ID')),
                ('registration_id', models.CharField(max_length=128, verbose_name='Registration ID')),
                ('registration', models.CharField(choices=[('1', 'Reguler'), ('P', 'Transfer')], default='1', max_length=2, verbose_name='Registration')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('ALM', 'Alumni'), ('DRO', 'Drop out'), ('MVD', 'Moved'), ('MSC', 'Misc')], default='ACT', max_length=128, verbose_name='Status')),
                ('status_note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Status note')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Person')),
                ('rmu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.ProgramStudy', verbose_name='Program Study')),
                ('year_of_force', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.SchoolYear', verbose_name='Year of force')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'permissions': (('register_student', 'Can Register New Student'),),
            },
        ),
    ]
