# Generated by Django 2.2.8 on 2020-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20200208_1659'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonAsStudent',
        ),
        migrations.CreateModel(
            name='StudentPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Student Personal',
                'verbose_name_plural': 'Student Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
    ]
