# Generated by Django 2.2.10 on 2020-02-20 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('academic', '0002_auto_20200217_0336'),
        ('students', '0002_auto_20200217_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('numeric', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Numeric Score')),
                ('alphabetic', models.CharField(max_length=1, verbose_name='Alphabetic Score')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='academic.CurriculumCourse', verbose_name='Course')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_students.studentscore_set+', to='contenttypes.ContentType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Score',
                'verbose_name_plural': 'Student Scores',
            },
        ),
        migrations.CreateModel(
            name='ConversionScore',
            fields=[
                ('studentscore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.StudentScore')),
                ('ori_code', models.CharField(max_length=128, verbose_name='Origin Code')),
                ('ori_name', models.CharField(max_length=128, verbose_name='Origin Name')),
                ('ori_numeric_score', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Origin Numeric')),
                ('ori_alphabetic_score', models.CharField(max_length=128, verbose_name='Origin Alphabetic')),
            ],
            options={
                'verbose_name': 'Conversion Score',
                'verbose_name_plural': 'Conversion Scores',
            },
            bases=('students.studentscore',),
        ),
    ]
