# Generated by Django 2.2.8 on 2020-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200126_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIDNumeratorMixin',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Register number'),
        ),
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Student ID'),
            preserve_default=False,
        ),
    ]
