# Generated by Django 2.2.10 on 2020-02-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200217_0336'),
        ('students', '0003_conversionscore_studentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='teachers.Teacher', verbose_name='Coach'),
        ),
    ]
