# Generated by Django 2.2.8 on 2020-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200126_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(editable=False, max_length=128, unique=True, verbose_name='Student ID'),
        ),
    ]
