# Generated by Django 2.2.8 on 2020-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200126_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(choices=[('1', 'Reguler'), ('P', 'Transfer')], default='1', max_length=2, verbose_name='Registration'),
        ),
    ]
