# Generated by Django 2.2.10 on 2020-02-25 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_histories_tab', models.BooleanField(default=True, help_text='Show formal person histories tab', verbose_name='Show histories tab')),
                ('show_formal_education_history', models.BooleanField(default=True, help_text='Show formal education histories panel', verbose_name='Show formal education')),
                ('show_nonformal_education_history', models.BooleanField(default=True, help_text='Show non formal education histories panel', verbose_name='Show non formal education')),
                ('show_working_history', models.BooleanField(default=True, help_text='Show working histories panel', verbose_name='Show working experience')),
                ('show_organization_history', models.BooleanField(default=True, help_text='Show organization histories panel', verbose_name='Show organization experience')),
                ('show_skill', models.BooleanField(default=True, help_text='Show skills panel', verbose_name='Show skill')),
                ('show_award', models.BooleanField(default=True, help_text='Show awards panel', verbose_name='Show award')),
                ('show_publication', models.BooleanField(default=True, help_text='Show publications panel', verbose_name='Show publication')),
                ('show_family', models.BooleanField(default=True, help_text='Show family or relationship tab', verbose_name='Show family tab')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Person Setting',
                'verbose_name_plural': 'Person Settings',
            },
        ),
    ]
