# Generated by Django 2.2.8 on 2020-01-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentitem',
            old_name='enrolment',
            new_name='enrollment',
        ),
    ]
