# Generated by Django 2.2.10 on 2020-02-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
        ('students', '0004_student_coach'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrolmentPlan',
            new_name='EnrollmentPlan',
        ),
    ]
