# Generated by Django 2.2.8 on 2020-01-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0002_enrollmentitem_lecture'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentitem',
            unique_together={('enrollment', 'lecture')},
        ),
    ]
