# Generated by Django 2.2.8 on 2020-01-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_auto_20200127_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentitem',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Remedy')], default=1, max_length=2, verbose_name='Status'),
        ),
    ]
