# Generated by Django 2.2.8 on 2020-01-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20200127_0416'),
        ('enrollments', '0003_enrollmentitem_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentitem',
            unique_together={('enrollment', 'lecture')},
        ),
    ]
