# Generated by Django 2.2.8 on 2020-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_auto_20200127_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
    ]
