# Generated by Django 2.2.10 on 2020-02-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_auto_20200223_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentplan',
            name='criteria',
            field=models.CharField(choices=[('1', 'NEW'), ('2', 'REMEDY')], default='1', max_length=2, verbose_name='Criteria'),
        ),
        migrations.AlterField(
            model_name='enrollmentplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='Student'),
        ),
    ]
