# Generated by Django 2.2.10 on 2020-02-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_coach'),
        ('lectures', '0002_auto_20200226_0332'),
        ('enrollments', '0005_auto_20200226_0554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentplan',
            unique_together={('student', 'lecture')},
        ),
    ]
