# Generated by Django 2.2.8 on 2020-01-27 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0004_auto_20200127_1248'),
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Register number')),
                ('inner_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('body', wagtail.core.fields.RichTextField(max_length=10000, verbose_name='Body')),
                ('attachment', models.ManyToManyField(to='wagtaildocs.Document', verbose_name='Attachment')),
                ('cc', models.ManyToManyField(related_name='cc', to='employees.Chairman', verbose_name='CC')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('receiver', models.ManyToManyField(related_name='memos_received', to='employees.Chairman', verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos_sent', to='employees.Chairman', verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
            },
        ),
    ]
