# Generated by Django 2.2.8 on 2020-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ememo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='sender',
        ),
        migrations.AlterField(
            model_name='memo',
            name='inner_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID'),
        ),
    ]
