# Generated by Django 2.2.8 on 2020-01-29 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ememo', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='cc',
            field=models.ManyToManyField(related_name='cc', to='employees.Chairman', verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='memo',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='memo',
            name='receiver',
            field=models.ManyToManyField(related_name='memos_received', to='employees.Chairman', verbose_name='Receiver'),
        ),
    ]
