# Generated by Django 2.2.8 on 2020-01-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('ememo', '0002_auto_20200128_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='attachment',
        ),
        migrations.AddField(
            model_name='memo',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.Document', verbose_name='Attachment'),
        ),
    ]
