# Generated by Django 2.2.8 on 2020-02-08 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_auto_20200208_1659'),
        ('persons', '0009_auto_20200208_1659'),
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsTeacher',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Employment',
                'verbose_name_plural': 'Teacher Employments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='PersonAsTeacher',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Personal',
                'verbose_name_plural': 'Teacher Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('tid', models.CharField(max_length=128, unique=True, verbose_name='Teacher ID')),
                ('is_nidn', models.BooleanField(default=False, verbose_name='ID is NIDN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('courses', models.ManyToManyField(to='academic.Course', verbose_name='Courses')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Employee')),
                ('rmu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academic.ResourceManagementUnit', verbose_name='Homebase')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
