# Generated by Django 2.2.8 on 2020-01-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAsTeacher',
            fields=[
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('fid', models.CharField(max_length=128, unique=True, verbose_name='Teacher ID')),
                ('is_nidn', models.BooleanField(default=False, verbose_name='ID is NIDN')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active status')),
                ('courses', models.ManyToManyField(to='academic.CurriculumCourse', verbose_name='Courses')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('homebase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.ProgramStudy', verbose_name='Homebase')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
