# Generated by Django 2.2.10 on 2020-02-15 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('academic', '0001_initial'),
        ('employees', '0002_auto_20200215_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEmployment',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Employment',
                'verbose_name_plural': 'Teacher Employments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='TeacherPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Personal',
                'verbose_name_plural': 'Teacher Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('tid', models.CharField(max_length=128, unique=True, verbose_name='Teacher ID')),
                ('is_nidn', models.BooleanField(default=False, verbose_name='ID is NIDN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('courses', models.ManyToManyField(to='academic.Course', verbose_name='Courses')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee', verbose_name='Employee')),
                ('rmu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='academic.ResourceManagementUnit', verbose_name='Homebase')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
