# Generated by Django 2.2.8 on 2020-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200208_1659'),
        ('persons', '0009_auto_20200208_1659'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAsTeacher',
        ),
        migrations.DeleteModel(
            name='PersonAsTeacher',
        ),
        migrations.CreateModel(
            name='TeacherEmployment',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Employment',
                'verbose_name_plural': 'Teacher Employments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='TeacherPersonal',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher Personal',
                'verbose_name_plural': 'Teacher Personals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('persons.person',),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='creator',
        ),
    ]
