# Generated by Django 2.2.10 on 2020-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_nidn',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Teacher ID'),
        ),
    ]
