# Generated by Django 2.2.10 on 2020-02-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=50, verbose_name='Counter period')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Counter')),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Numerator',
                'verbose_name_plural': 'Numerators',
                'unique_together': {('ctype', 'dtype', 'date_start', 'date_end')},
            },
        ),
    ]
