# Generated by Django 2.2.8 on 2020-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerators', '0002_auto_20200201_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerator',
            name='dtype',
            field=models.CharField(choices=[('Y', 'Yearly'), ('M', 'Montly'), ('F', 'Fixed')], default='Y', max_length=50, verbose_name='Counter period'),
        ),
    ]
