# Generated by Django 2.2.8 on 2020-01-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('numerators', '0004_auto_20200201_0222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numerator',
            unique_together={('ctype', 'dtype', 'date_start', 'date_end')},
        ),
    ]
