# Generated by Django 2.2.8 on 2020-01-26 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
    ]
