# Generated by Django 2.2.8 on 2020-01-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200128_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='inner_id',
        ),
    ]
