# Generated by Django 2.2.8 on 2020-01-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.SlugField(max_length=256, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('teaching_method', models.CharField(max_length=256, verbose_name='Teaching method')),
                ('course_type', models.CharField(choices=[('A', 'Mandatory'), ('B', 'Choice'), ('C', 'Interest Mandatory'), ('D', 'Interest Choice'), ('S', 'Research/Thesis/Disertation')], default='A', max_length=1, verbose_name='Course type')),
                ('course_group', models.CharField(choices=[('A', 'MPK: Personal Development Course'), ('B', 'MKK: Knowledge Foudation Course'), ('C', 'MKB: Creational Skill Course'), ('D', 'MPB: Behavioral Skill Course'), ('E', 'MBB: Life Skill Course'), ('F', 'MKDU: Basic Knowledge Course'), ('G', 'MKDK: Basic Skill Course')], default='A', max_length=4, verbose_name='Course group')),
                ('description', wagtail.core.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('equal_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.Course', verbose_name='Equal to')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Code')),
                ('year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], default='2019', max_length=4, verbose_name='Year')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('sks_graduate', models.PositiveIntegerField(default=0, verbose_name='SKS graduate')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('alias', models.CharField(blank=True, max_length=512, null=True, verbose_name='Alias')),
            ],
            options={
                'verbose_name': 'Program Study',
                'verbose_name_plural': 'Program Studies',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.SlugField(max_length=256, unique=True, verbose_name='Code')),
                ('year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044'), ('2045', '2045'), ('2046', '2046'), ('2047', '2047'), ('2048', '2048'), ('2049', '2049')], default='2019', max_length=4, verbose_name='Year')),
                ('semester', models.CharField(choices=[('1', 'Odd'), ('2', 'Even'), ('3', 'Short')], default='1', max_length=2, verbose_name='Semester')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
            ],
            options={
                'verbose_name': 'School Year',
                'verbose_name_plural': 'School Years',
            },
        ),
        migrations.CreateModel(
            name='ResourceManagementUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.SlugField(max_length=256, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.ResourceManagementUnit', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Resource Management Unit',
                'verbose_name_plural': 'Resource Management Unit',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('code', models.CharField(max_length=256, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('alias', models.CharField(blank=True, max_length=512, null=True, verbose_name='Alias')),
                ('level', models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S1', max_length=3, verbose_name='Level')),
                ('description', wagtail.core.fields.RichTextField(blank=True, max_length=10000, null=True, verbose_name='Description')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Faculty', verbose_name='Requisite')),
                ('rmu', mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU')),
            ],
            options={
                'verbose_name': 'Program Study',
                'verbose_name_plural': 'Program Studies',
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('sks', models.PositiveIntegerField(default=0, verbose_name='SKS')),
                ('sks_type', models.CharField(choices=[('M', 'Meeting'), ('P', 'Practice'), ('F', 'Field Practice'), ('S', 'Simulation')], default='M', max_length=1, verbose_name='SKS type')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Course', verbose_name='Course')),
                ('curricullum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Curriculum', verbose_name='Curriculum')),
            ],
            options={
                'verbose_name': 'Curricullum Course',
                'verbose_name_plural': 'Curricullum Courses',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='prodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.ProgramStudy', verbose_name='Program Study'),
        ),
        migrations.CreateModel(
            name='CoursePreRequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='C', max_length=2, verbose_name='Min Graduated Score')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_prerequisites', to='academic.Course', verbose_name='Course')),
                ('requisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisites', to='academic.Course', verbose_name='Requisite')),
            ],
            options={
                'verbose_name': 'Course Pre Requisite',
                'verbose_name_plural': 'Course Pre Requisite',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='rmu',
            field=mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
        ),
    ]
