# Generated by Django 2.2.8 on 2020-01-19 05:53

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rmu',
            field=mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='rmu',
            field=mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='rmu',
            field=mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
        ),
        migrations.AlterField(
            model_name='programstudy',
            name='rmu',
            field=mptt.fields.TreeForeignKey(help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
        ),
    ]
