# Generated by Django 2.2.8 on 2020-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20200119_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstudy',
            name='education_level',
        ),
        migrations.AddField(
            model_name='programstudy',
            name='level',
            field=models.CharField(choices=[('S1', 'Bachelor'), ('S2', 'Master'), ('S3', 'Doctor')], default='S1', max_length=3, verbose_name='Level'),
        ),
    ]
