# Generated by Django 2.2.8 on 2020-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20200126_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='semester_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1, verbose_name='SKS type'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='semester_type',
            field=models.CharField(choices=[('1', 'Odd'), ('2', 'Even')], default='1', max_length=1, verbose_name='SKS type'),
        ),
    ]
