# Generated by Django 2.2.8 on 2020-01-26 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20200126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='semester_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='semester_type',
            field=models.CharField(choices=[('1', 'Odd'), ('2', 'Even')], default='1', max_length=1, verbose_name='Odd/Event'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='programstudy',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='programstudy',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='resourcemanagementunit',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='resourcemanagementunit',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together={('curricullum', 'course')},
        ),
    ]
