# Generated by Django 2.2.8 on 2020-01-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20200119_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='name',
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='semester',
            field=models.CharField(choices=[('1', 'Ganjil'), ('2', 'Genap'), ('3', 'Short')], default='1', max_length=2, verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], default='2019', max_length=4, verbose_name='Year'),
        ),
    ]
