# Generated by Django 2.2.8 on 2020-01-26 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20200127_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='semester',
            field=models.CharField(choices=[('1', 'Odd'), ('2', 'Even'), ('P', 'Short')], default='1', max_length=2, verbose_name='Semester'),
        ),
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date modified')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('date_end', models.DateField(verbose_name='Date end')),
                ('activity', wagtail.core.fields.RichTextField(verbose_name='Activity')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('ONG', 'On Going'), ('END', 'End')], default='PND', max_length=3, verbose_name='Status')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.AcademicYear', verbose_name='Academic Year')),
            ],
            options={
                'verbose_name': 'Academic Activity',
                'verbose_name_plural': 'Academic Activities',
            },
        ),
    ]
