# Generated by Django 2.2.8 on 2020-01-26 18:10

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20200127_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicactivity',
            name='rmu',
            field=mptt.fields.TreeForeignKey(default=2, help_text='Resource Management Unit', on_delete=django.db.models.deletion.PROTECT, to='academic.ResourceManagementUnit', verbose_name='RMU'),
            preserve_default=False,
        ),
    ]
