# Generated by Django 2.2.8 on 2020-01-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_auto_20200127_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicactivity',
            options={'ordering': ('-date_start',), 'verbose_name': 'Academic Activity', 'verbose_name_plural': 'Academic Activities'},
        ),
    ]
