# Generated by Django 2.2.8 on 2020-01-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_auto_20200127_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumcourse',
            name='sks_type',
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='sks_field_practice',
            field=models.PositiveIntegerField(default=0, verbose_name='SKS Field'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='sks_meeting',
            field=models.PositiveIntegerField(default=0, verbose_name='SKS Meeting'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='sks_practice',
            field=models.PositiveIntegerField(default=0, verbose_name='SKS Practice'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='sks_simulation',
            field=models.PositiveIntegerField(default=0, verbose_name='SKS Simulation'),
        ),
    ]
