# Generated by Django 2.2.8 on 2020-01-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_auto_20200127_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumcourse',
            name='sks',
        ),
        migrations.AddField(
            model_name='course',
            name='has_dictate',
            field=models.BooleanField(default=True, verbose_name='Has dictate'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_lpu',
            field=models.BooleanField(default=True, help_text='Lecture Program Unit', verbose_name='Has LPU'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_practice_program',
            field=models.BooleanField(default=True, verbose_name='Has practice program'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_syllabus',
            field=models.BooleanField(default=True, verbose_name='Has syllabus'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_teaching_material',
            field=models.BooleanField(default=True, verbose_name='Has teaching material'),
        ),
    ]
