# Generated by Django 2.2.8 on 2020-01-27 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='', max_length=256, verbose_name='Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity'),
        ),
    ]
