# Generated by Django 2.2.8 on 2020-01-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_registration_enabled', models.BooleanField(default=True, help_text='Activate user registration form', verbose_name='User registration enabled')),
                ('auto_create_person', models.BooleanField(default=True, help_text='Create person data for new user created', verbose_name='Auto create person')),
                ('login_with_twitter', models.BooleanField(default=True, help_text='Activate login with Twitter', verbose_name='Login with Twitter')),
                ('login_with_facebook', models.BooleanField(default=True, help_text='Activate login with Facebook', verbose_name='Login with Facebook')),
                ('login_with_google', models.BooleanField(default=True, help_text='Activate login with Google', verbose_name='Login with Google')),
                ('login_with_github', models.BooleanField(default=True, help_text='Activate login with Github', verbose_name='Login with Github')),
                ('login_with_slack', models.BooleanField(default=True, help_text='Activate login with Slack', verbose_name='Login with Slack')),
                ('default_new_user_group', models.ForeignKey(help_text='Include new registered user to this group', on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='Registration default group')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
