# Generated by Django 2.2.8 on 2020-01-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='default_new_user_group',
            field=models.ForeignKey(blank=True, help_text='Include new registered user to this group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Registration default group'),
        ),
    ]
