# Generated by Django 2.2.8 on 2020-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_auto_20200129_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.order',),
        ),
        migrations.CreateModel(
            name='LabOrderProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Lab Order Item',
                'verbose_name_plural': 'Lab Order Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.orderproduct',),
        ),
    ]
