# Generated by Django 2.2.8 on 2020-02-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-date_created'], 'permissions': (('changeother_discussion', 'Can change other Discussion'), ('deleteother_discussion', 'Can delete other Discussion')), 'verbose_name': 'Discuss', 'verbose_name_plural': 'Discusses'},
        ),
    ]
